### PR TITLE
Topic/task pruning

### PR DESCRIPTION
**Pull request by mpilquist**
Fixes #669 by removing `onFinish` completely. /cc @ceedubs @djspiewak

### CODE REVIEW

**Comment by mpilquist** [comment]
Merge after #672

**Comment by ceedubs** [comment]
👍 for removing `Task.onFinish`. I can't really speak to the other changes.

**Comment by pchiusano** [comment]
@djspiewak any comments? I think this is exactly what you advocated in #669 but pipe up if not. Will merge later today or tomorrow if don't hear back.

**Comment by djspiewak** [comment]
Looks like basically what I would want!

**Pull request merged**
