### PR TITLE
Delete fs2.concurrent.once

### PR DESCRIPTION
**Pull request by SystemFw**
Depends  on https://github.com/typelevel/cats-effect/pull/328

### CODE REVIEW

**Comment by SystemFw** [comment]
`memoize` is in cats-effect now, so this can be merged

**Comment by SystemFw** [comment]
ah, I actually didn't know what was that for! 
Will do that then, just a sec

**Comment by SystemFw** [comment]
ugh, added this and then realised the old wording is different. Do you prefer we keep what was there before?

**Comment by mpilquist** [comment]
No strong preference

**Pull request merged**
