### PR TITLE
Added a simple queue test, which currently hangs

### PR DESCRIPTION
**Pull request by pchiusano**
Also some documentation and other cleanup.

@pchlupacek can you take a look at my test and see if you spot anything silly?

### CODE REVIEW

**Comment by pchiusano** [comment]
Here's the test:

```Scala
  property("unbounded producer/consumer") = forAll { (s: PureStream[Int]) =>
    Stream.eval(async.unboundedQueue[Task,Int]).map { q =>
      val r = run(s.get)
      println("unbounded producer/consumer test: " + r)
      run(q.dequeue.merge(s.get.evalMap(q.enqueue1).drain).take(r.size)) == r
    } === Vector(true)
  }
```

Which prints:

```
unbounded producer/consumer test: Vector()
unbounded producer/consumer test: Vector(-1280647181)
```

**Comment by pchlupacek** [comment]
@pchiusano sure will dive on that over weekend.

**Comment by pchiusano** [comment]
@pchlupacek did you get a chance to look at this yet?

**Comment by pchlupacek** [comment]
was little bit under pressure before christmas sorry. Is on my priority 1 this week. Would it still be ok if I take look on this tmrw?

**Comment by pchiusano** [comment]
Sure :)

**Comment by pchiusano** [comment]
Okay, I'm going to go ahead and merge this, looks like #514 fixed this too! @pchlupacek, @mpilquist made it easy for you. :)

**Comment by pchlupacek** [comment]
@pchiusano I know... Thanks a lot again @mpilquist ... Its the typical error I do all the times. The Unit in scala is just killing me all the time.

**Comment by pchiusano** [comment]
Yeah you do not really get any help from the typechecker to avoid mistakes
like this.

**Comment by mpilquist** [comment]
@pchlupacek No worries -- I'm glad it was a simple fix in the end. :smile:

**Pull request merged**
