### PR TITLE
Implementation of `observe`, `observeAsync`, and `diamond` combinator

### PR DESCRIPTION
**Pull request by pchiusano**
As discussed in #501.

Currently in `async.channel` package. Not totally sold on that. But it does raise the possibility of still having another `channel` package in `fs2.channel` for more synchronous stuff.

This is not tested, maybe we should hold off on merging until we experiment with the API some and add some tests. 

I went with just having the `diamond` combinator take a regular `Queue`. I think it adds too much complexity to have a separate `QueueStrategy` type. Just don't reuse the same queue you are using elsewhere. And if you do, be prepared for weird behavior.

### CODE REVIEW

**Comment by pchiusano** [comment]
Also, fyi I am going to be on holiday starting tomorrow through Jan 5th, so I probably won't be as responsive between now and then, but I'll reply to threads when I can. :)

**Comment by pchlupacek** [comment]
ok no prob. I gonna experiment with sinks. I have WIP on kafka driver, will try to implement it with fs2 so we will see what still missing. I may also do some PRs on closable signal and queue. Take care!

**Comment by pchlupacek** [comment]
@pchiusano I have played a bit with various ways on sinks and channels, and Just for curiosity, have you considered : 
```scala
type Channel[F,A,B] = Stream[F,Stream[F,A] => Stream[F,B]]  ???
```
To me this works nicely to implement, lift, observe, through, while still keeping chunkiness and lot of flexibility like the pure function. In fact for observe, through et all I was thinking of slightly modified signature like 
```
type Channel[F,A,B] = Stream[F,Stream[Pure,A] => Stream[F,B]]
```
but that would limit some composability, in fact. 

I like on first signature that you can do things like 
``` scala
(ch1 zip ch2) map (_ andThen _) 
``` 
mapOut, mapIn etc will be easy to implement too. 

I would say the only problematic is `pipeIn` and `pipeOut`, like we had in old implementation, but I think this is ok, as we can use similar technique like you proposing in diamond to implement them. In fact Perhaps introducing `SynchronousQueue` to async would be beneficial for these situations.

**Comment by pchlupacek** [comment]
Just to clarify. I see this suffers from option (3) limitations too, but not necessarily big deal imho. For example to construct functions that depends on result of the last invocation may be in fact quite ok:

```scala

val state : F[Signal[F,Boolan]] = ???
def write(full:Boolean, r: R)(src:Stream[F,A]):Stream[F,(Boolean,A)] = ??? // implement write to R, that will drop if full == true , echoing full at the output. 

val channel: Channel[F,A, (Boolean,A)] = bracket(acuireR)(r=>  state.continuous.map { full => write(full,r) _ }, cleanup = releaseR )

```

**Comment by mpilquist** [comment]
Note: this work is now on topic/redesign -- Paul merged it in to topic/redesign-simple-interpreter before that branch was merged. I'm closing this but if there are any more comments, feel free to reopen or file individual issues.

**Pull request closed without merging**
