### PR TITLE
Backport #1311 (fix for #1297) to 0.10

### PR DESCRIPTION
**Pull request by vpavkin**
We still have some projects on 0.10.6 and are affected by #1297.

### CODE REVIEW

**Comment by vpavkin** [comment]
Travis fails with MiMa, but this is 0.* series and I hope we can live with this here?

**Comment by mpilquist** [comment]
@vpavkin We can't break binary compatibility in a 0.10 point release. While not particularly elegant, one fix could be dynamically testing if the received `Concurrent[F]` is an instance of `ConcurrentEffect[F]` and if so, using the new algorithm here.

**Comment by vpavkin** [comment]
@mpilquist Thanks for your suggestion. I re-made it that way.

**Comment by vpavkin** [comment]
Sorry for rushing in again, but could someone from maintainers, please, take a look and make a release if there are no issues left? :)
Thanks! I wouldn't bump it that soon if it was not a live issue for us :)

**Comment by mpilquist** [comment]
@vpavkin I can do a release in a few minutes -- just to confirm, you've tried this fix in your system and saw it work?

**Comment by vpavkin** [comment]
Sympthoms are so similar to #1297 so (shame on me) we haven't yet. It will require time anyway, since hangs are non-deterministic and we got a hanged stream serveral days after deploying fs2-based impl.

If this is a prerequisite for a bugfix release I will deploy a fixed version today with locally published artifact.

**Comment by mpilquist** [comment]
Not a strict prerequisite but it would be helpful. If it's too much work, that's fine, just let me know. :)

**Comment by vpavkin** [comment]
Deployment is planned for this evening (Europe). So we'll monitor for a week or so. if there're no hangs then we can say it help with a more or less high level of certainty.
I'll get back to you in a week :)

**Comment by mpilquist** [comment]
0.10.7 has been released -- https://github.com/functional-streams-for-scala/fs2/releases/tag/v0.10.7

**Comment by vpavkin** [comment]
Thank you :tada:!

**Pull request merged**
