### PR TITLE
Added file/directory watching support to fs2.io.file based on NIO WatchService

### PR DESCRIPTION
**Pull request by mpilquist**

### CODE REVIEW

**Comment by mpilquist** [comment]
@SystemFw Would you do a review of this? Thanks!

**Comment by SystemFw** [comment]
Will do :)

**Comment by SystemFw** [comment]
I'll get to this tomorrow

**Comment by SystemFw** [comment]
The user facing API looks great. 
The implementation also looks good to me: the extra complexity from recursive watching and single file watching is justified imo. I definitely wouldn't want users to have to implement that.

**Pull request merged**
