### PR TITLE
add `toInputStreamResource` 

### PR DESCRIPTION
**Pull request by wedens**
I think it makes sense considering `toInputStream`  returned singleton stream.

Not sure what to do with bin compat though. Is there some branch for breaking changes?

### CODE REVIEW

**Comment by mpilquist** [comment]
This is a great idea. If we want to fix this in the 1.0 series, we could introduce a new name for the version that returns a resource -- `toInputStreamResource` perhaps. Then have the pipe version use the `toInputStreamResource` method in its implementation.

There's no series/1.1 yet -- we're working on a new interpreter on the topic/fs3 branch but it's a bit early to PR stuff there yet unless the changes are related to the interpreter.

**Comment by SystemFw** [comment]
Data point: for `hold`, which is in a similar situation, I added `holdResource`.
Ideally we would just change it, but we can't break the api, as you point out

**Comment by wedens** [comment]
> we could introduce a new name for the version that returns a resource -- toInputStreamResource perhaps. Then have the pipe version use the toInputStreamResource method in its implementation.

I've implemented this suggestion.

**Comment by mpilquist** [comment]
@wedens This looks ready to merge to me once we add the mima exclusion for binary compatibility of `JavaInputOutputStream`.

**Comment by wedens** [comment]
@mpilquist Done.

**Comment by SystemFw** [comment]
Thank you!

**Pull request merged**
