### PR TITLE
Minor performance improvements in Free

### PR DESCRIPTION
**Pull request by mpilquist**
This PR implements a few minor performance improvements, including:
 - Removing `Free#step` in favor of doing associativity fixups directly in `flatMap`
 - Added `Free.Map` constructor and implemented map fusion, along with cooperative associativity fixups between `flatMap` and `map`
 - Replacing `runTranslate` with `run` (negligible improvement but simplifies code)

The removal of `step` didn't make much improvements in the benchmark (as long as the benchmark covers both the building of the `Free` as well as the running of it). This includes using polymorphic subtype method dispatch to fixup associativity.

Map fusion resulted in a 3x performance improvement for the consecutive map test.

a0aef44d45e76ebfe6b24aee3fa71664b7bbca0e (head of series/1.0 at time of opening)
```
[info] Benchmark                      Mode  Cnt   Score   Error  Units
[info] FreeBenchmark.nestedFlatMaps  thrpt   10  11.023 ± 1.311  ops/s
[info] FreeBenchmark.nestedMaps      thrpt   10   7.292 ± 1.810  ops/s
```

9d69b8fe480efaa6620ceedfa166f9b1427de7f6 (with step removed and without Map constructor)
```
[info] Benchmark                      Mode  Cnt   Score   Error  Units
[info] FreeBenchmark.nestedFlatMaps  thrpt   10  11.254 ± 1.081  ops/s
[info] FreeBenchmark.nestedMaps      thrpt   10   7.266 ± 3.232  ops/s
```

8ebd5a0f93591962e27452b8f17fff96d81ffe1d (The final commit in this PR at time of opening)
```
[info] Benchmark                             Mode  Cnt   Score   Error  Units
[info] FreeBenchmark.alternatingMapFlatMap  thrpt   10  11.207 ± 4.787  ops/s
[info] FreeBenchmark.nestedFlatMaps         thrpt   10  12.372 ± 3.718  ops/s
[info] FreeBenchmark.nestedMaps             thrpt   10  21.336 ± 2.183  ops/s
```

### CODE REVIEW

**Comment by mpilquist** [comment]
Bah, this introduces a stack safety issue due to the unbounded fusing of maps. There are a few different ways to fix:
# Limit the number of map fusions before inserting a trampoline (bind)
# Represent map constructor with a type aligned sequence of functions
# Represent map constructor with a list of untyped functions ;)

I have a different idea entirely though, which reintroduces a step function but eagerly steps `Bind(Pure(..), ..)` patterns without breaking `suspend` like it used to.

**Comment by djspiewak** [comment]
Idea 2 seems very doable.  I can jump on that if you would like and see how it goes.  I'll note though that this effectively becomes a relatively lightweight trampoline.

**Comment by djspiewak** [comment]
> If by idea 2, you were referring to the eager application

No, I meant the type-aligned seq of functions.  But I like the eager `Bind(Pure` idea as well.

**Comment by mpilquist** [comment]
Cool, I'll leave the type aligned sequence to you and I'll work on the suspend/Pure constructor change. Want me to move this stuff to a branch in the official repo?

**Pull request closed without merging**
