### PR TITLE
Added special handling of Uncons and CloseScope in case of interrupt

### PR DESCRIPTION
**Pull request by pchlupacek**
@mpilquist there is the fix. 

I am still thinking of more proper way of interruption. I think there must be proper way to do it just in compile.

### CODE REVIEW

**Comment by mpilquist** [comment]
Awesome, thanks. I suspect we'll still have failures in at least the async resource allocation tests, unrelated to interruption -- tests 3 and 6 have failed on Travis since we merged the Algebra refactor.

**Comment by pchlupacek** [comment]
But would open another PR if I will find reasons for that and fix

**Comment by mpilquist** [comment]
@pchlupacek SemaphoreSpec failed: https://travis-ci.org/functional-streams-for-scala/fs2/jobs/325132310#L885

**Comment by pchlupacek** [comment]
@mpilquist was looking up the semaphore failure but somehow the link you pasted is just refering to `- dequeueAvailable (118 milliseconds)` that seems to be passing. By any chance do you have the correct link?

**Comment by mpilquist** [comment]
@pchlupacek Not sure, I guess Travis deleted that build log. I'll keep looking for it to repeat in subsequent builds.

**Comment by pchlupacek** [comment]
@mpilquist excellent, thanks a lot

**Pull request merged**
