### PR TITLE
Bugfix/queue get

### LINKED ISSUE #1293: Queue (consistently) misses an element on certain usage
When a dequeue stream is manipulated (merged with another stream, and split into two via pull), then dequeuing misses an element (always the first element on a subsequent pull). an example of the code showing this can be seen here: https://scastie.scala-lang.org/LBTK7fSnQIC0kLEkvk9cYA

Not only the element (4) is missing from the second printed list, but it is also not shown in the dequeue's evalTap logging - there is no "deq: 4" line.

This behaviour is also consistent - all repeated runs result in the same error.

`run1` in the example is added as a passing example - if the stream is split by amount, dequeuing works ok.

related conversation (in case there are more replies) on gitter starts here: https://gitter.im/functional-streams-for-scala/fs2?at=5bc642ed82893a2f3bf0cef9

fs2 version: 1.0.0
The same function (`splitByTimeout`) was working ok with an earlier fs2 release (0.10.x)

### PR DESCRIPTION
**Pull request by pchlupacek**
Fixes #1293. 

Needs to be squashed before merge.

### CODE REVIEW

**Comment by pchlupacek** [comment]
huh travis complains about bincompat? All I have touched is private, so this seems odd :-(

**Comment by mpilquist** [comment]
We can add an exclusion for the Travis error.

Does this test pass too?

```scala
      Queue
         .unbounded[IO, Int]
         .flatMap { q =>
           q.dequeue.timeout(1.second) *>
             q.enqueue1(1) *>
             q.enqueue1(2) *>
             q.dequeue1
         }
         .unsafeRunSync shouldBe 1
```

**Comment by pchlupacek** [comment]
@mpilquist tests passes. As regard the exclusions, where to add them ?

**Comment by mpilquist** [comment]
https://github.com/functional-streams-for-scala/fs2/blob/series/1.0/build.sbt#L197

**Comment by pchlupacek** [comment]
Also going forward perhaps fro next release of fs2, I would like to explore, if we could implement `Stream.bracket` with similar signatures, essentially making `canceling` a stream instead of `interrupting` it. I think it could be possible and have bracket propagate the `Case` to finalizer, similarly like `Bracket` does in cats.

**Pull request merged**
