### PR TITLE
Add Chunk.BytesVector as a view into concatenated Chunk.Bytes instances.

### PR DESCRIPTION
**Pull request by greg-a-atkinson**
A chunk implementation representing concatenated Chunk.Bytes instances as an alternative to copying them into new arrays:

`final case class BytesVector private (chunks: Vector[Chunk.Bytes], length: Int) extends Chunk[Byte]`

PR raised for discussion and not yet ready to me merged without tests and further input.

### CODE REVIEW

**Comment by mpilquist** [comment]
I'd like to see the performance of this compared to using `Chunk.ByteVector` directly, which wraps a single `scodec.bits.ByteVector`. I strongly suspect that using `scodec.bits.ByteVector` and its `++` operation along with its `view` constructor will generally beat using a `Vector[Chunk[Byte]]`. The `Chunk.ByteVector` class could probably be optimized some more like the implementation in this PR.

**Comment by greg-a-atkinson** [comment]
> I'd like to see the performance of this compared to using `Chunk.ByteVector` directly, which wraps a single `scodec.bits.ByteVector`. I strongly suspect that using `scodec.bits.ByteVector` and its `++` operation along with its `view` constructor will generally beat using a `Vector[Chunk[Byte]]`. The `Chunk.ByteVector` class could probably be optimized some more like the implementation in this PR.

Agreed. This is something I’m going to try. Thanks for pointing it out.

**Comment by greg-a-atkinson** [comment]
> I'd like to see the performance of this compared to using `Chunk.ByteVector` directly, which wraps a single `scodec.bits.ByteVector`. I strongly suspect that using `scodec.bits.ByteVector` and its `++` operation along with its `view` constructor will generally beat using a `Vector[Chunk[Byte]]`. The `Chunk.ByteVector` class could probably be optimized some more like the implementation in this PR.

A rough, but reasonable performance comparison using a single 416MB json document with 38,831,305 tokens, was tokenised by the proposed Chunk.BytesVector in 11.894 seconds and by the recommended codec.bits.ByteVector in 7.871 seconds. I’m happy with that and even more so that ByteVector was a drop-in replacement. Thanks!

**Comment by mpilquist** [comment]
Awesome! Thanks for trying that experiment. `ByteVector` is fairly well optimized. ;)

**Pull request closed without merging**
