### PR TITLE
Updated sbt version to 0.13.9

### PR DESCRIPTION
**Pull request by zaneli**

### CODE REVIEW

**Comment by zaneli** [comment]
I have confirmed that all build jobs succeeded in my repository. :(
https://travis-ci.org/zaneli/fs2/builds/97018409

**Comment by zaneli** [comment]
Sorry, I will try to build job succeed on any Travis platform.
Would you wait to merge?

**Comment by zaneli** [comment]
I guess the difference of build success or failure is depends build on Docker or not,
so I added `sudo: false` explicitly.

I do not know the circumstances of this commit https://github.com/functional-streams-for-scala/fs2/commit/2d3b6c54dbf074b248242e34c9dee714a0da797c,
but it seems to be fine now.

**Comment by pchiusano** [comment]
Will take a look at look at this today, I think should be fine to merge.

**Comment by pchiusano** [comment]
Okay, seems fine to me, merging, thanks!

**Comment by zaneli** [comment]
It's my pleasure.

**Pull request merged**
