### PR TITLE
Encapsulate CompileScope methods

### PR DESCRIPTION
**Pull request by diesalbla**
Narrow the CompileScope class. We remove the method "openAncestor", and hide as private `findSelfOrAncestor` and `findSelfOrChild`. We expose two methods, `descendsFrom` (a Boolean query), and the `closeRelative` method, which includes the logic to find a related scope, close it, and return any error that was risen in that Scope. We add documentation for these methods.

We rewrite the code of the `compileLoop-go` for the `CloseScope` node. We use of the `closeRelative` method. This removes the `closeAndGo`.

### CODE REVIEW

**Comment by pchlupacek** [comment]
Could you please elaborate on benefits of this change?

**Comment by diesalbla** [comment]
> Could you please elaborate on benefits of this change?

- It reduces the API of the `CompileScope` class, avoiding the need to expose the "family tree" of the compile scopes. 
- The changes also make the compilation case for the `CloseScope` operation more readable: by removing the inner method `closeAndGo` the flow in that case is top-down.
- It also adds or clarifies some comments.

**Comment by pchlupacek** [comment]
I am not seeing enough benefits for this. My feeling is that this is just different approach to the implementation that is already there. As there are no performance/correctness improvements and scope's api is in fact private to fs2, I am -1 on this.

**Comment by diesalbla** [comment]
This code has been changed in `series/1.1`, so this is no longer needed.

**Pull request closed without merging**
