### PR TITLE
Added tcp.SSLSocket

### PR DESCRIPTION
**Pull request by pchlupacek**
Initial SSL implementation. @pchiusano , @mpilquist , @djspiewak  any ideas how to test this? 

Thanks

### CODE REVIEW

**Comment by djspiewak** [comment]
Round tripping is probably the best we can do.

**Comment by pchlupacek** [comment]
@djspiewak yeah :-)

**Comment by pchiusano** [comment]
Should this be TLSSocket?

**Comment by pchlupacek** [comment]
actually no strong opinion on naming. However TLS is just one of the possible options SSLEngine supports. On other hand if we will name it TLS we can then swap later implementation of TLS for something truly non-blocking instead of SSLEngine and be consistent. 

thoughts @pchiusano?

**Comment by mpilquist** [comment]
👍 for TLS despite the names in JSSE. Also, given how notoriously difficult it is to securely configure SSLEngine/SSLContext, I'd like to have easy integration with https://github.com/typesafehub/ssl-config -- not a JAR dependency but just appropriate constructors that would allow a user to use both ssl-config-core library with FS2.

**Comment by mpilquist** [comment]
@pchlupacek What's the state of this?

**Comment by pchlupacek** [comment]
We using this in production already, part of fs2-http. Once we sort of agree on naming and modifications I am able to update PR. 

Also not sure what we do about this configuration topic you mentioned. Perhpas that could be another issue once this gets merged ?

**Comment by pchlupacek** [comment]
@mpilquist was thinking about this. I will refactor this against 1.0 once fast will get merged ok ?

**Comment by mpilquist** [comment]
@pchlupacek Yep that sounds good. I'm hoping to merge topic/fast this week.

**Comment by mpilquist** [comment]
@pchlupacek When you get a chance, a 0.10 version of this PR would be great.

**Pull request closed without merging**
