### PR TITLE
No Sync for compileLoop

### PR DESCRIPTION
**Pull request by diesalbla**
The `Sync` is only needed in the call to `suspend`, to recur through the `GetScope` case.

### CODE REVIEW

**Comment by diesalbla** [comment]
@pchlupacek The `git` history indicates that the `F.suspend` was introduced in [this commit](https://github.com/functional-streams-for-scala/fs2/commit/4eeeeab4383f9dd4ae37be7597ba50eb06ac910b). Can you remember why  was it necessary, and if it still is? So far, the tests pass.

**Comment by pchlupacek** [comment]
Yes I bet this was stack safety issue. Perhaps due to changes to compiler this is not necessary, but I would suggest to do more tests with deep translate and interpreter nesting

**Comment by djspiewak** [comment]
Just looking at it, without looking at the bytecode, it doesn't look necessary for stack safety, or anything else really. We should sanity check the compiled invocation. I've seen the compiler sometimes fail to recognize a tail call on a function which encodes a gadt skolem, but that bug may also be fixed.

**Comment by diesalbla** [comment]
@djspiewak I think that those problems in the compiler, between tail calls and GADT skolems, is what I found in https://github.com/functional-streams-for-scala/fs2/pull/1529#issuecomment-506913209.

**Comment by djspiewak** [comment]
It works on 2.12:

```
     439: aload         18
     441: instanceof    #50                 // class fs2/internal/Algebra$GetScope
     444: ifeq          473
     447: aload_1
     448: aload         17
     450: invokevirtual #466                // Method fs2/internal/FreeC$ViewL$View.next:()Lscala/Function1;
     453: getstatic     #472                // Field fs2/internal/FreeC$Result$.MODULE$:Lfs2/internal/FreeC$Result$;
     456: aload_1
     457: invokevirtual #767                // Method fs2/internal/FreeC$Result$.pure:(Ljava/lang/Object;)Lfs2/internal/FreeC$Result;
     460: invokeinterface #479,  2          // InterfaceMethod scala/Function1.apply:(Ljava/lang/Object;)Ljava/lang/Object;
     465: checkcast     #79                 // class fs2/internal/FreeC
     468: astore_2
     469: astore_1
     470: goto          0
```

**Comment by djspiewak** [comment]
And on 2.11:

```
     440: aload         16
     442: instanceof    #186                // class fs2/internal/Algebra$GetScope
     445: ifeq          474
     448: aload_1
     449: aload         15
     451: invokevirtual #362                // Method fs2/internal/FreeC$ViewL$View.next:()Lscala/Function1;
     454: getstatic     #370                // Field fs2/internal/FreeC$Result$.MODULE$:Lfs2/internal/FreeC$Result$;
     457: aload_1
     458: invokevirtual #548                // Method fs2/internal/FreeC$Result$.pure:(Ljava/lang/Object;)Lfs2/internal/FreeC$Result;
     461: invokeinterface #379,  2          // InterfaceMethod scala/Function1.apply:(Ljava/lang/Object;)Ljava/lang/Object;
     466: checkcast     #127                // class fs2/internal/FreeC
     469: astore_2
     470: astore_1
     471: goto          0
```

I really don't think the `suspend` is necessary. I'll check 2.13 to be thorough, but I'm sure the behavior hasn't regressed.

**Comment by djspiewak** [comment]
And 2.13:

```
     436: goto          439
     439: aload         18
     441: instanceof    #50                 // class fs2/internal/Algebra$GetScope
     444: ifeq          473
     447: aload_1
     448: aload         17
     450: invokevirtual #456                // Method fs2/internal/FreeC$ViewL$View.next:()Lscala/Function1;
     453: getstatic     #462                // Field fs2/internal/FreeC$Result$.MODULE$:Lfs2/internal/FreeC$Result$;
     456: aload_1
     457: invokevirtual #755                // Method fs2/internal/FreeC$Result$.pure:(Ljava/lang/Object;)Lfs2/internal/FreeC$Result;
     460: invokeinterface #469,  2          // InterfaceMethod scala/Function1.apply:(Ljava/lang/Object;)Ljava/lang/Object;
     465: checkcast     #79                 // class fs2/internal/FreeC
     468: astore_2
     469: astore_1
     470: goto          0
```

**Pull request merged**
