### PR TITLE
Make sure MessageDigest respects Chunk size and offset

### PR DESCRIPTION
**Pull request by SystemFw**
Fixes #943

### CODE REVIEW

**Comment by adamretter** [comment]
Thanks for fixing this so quickly :-)

Just one comment - Would have been nice to see a test as well to prevent regressions. I did add a test to my PR for that purpose.

**Comment by SystemFw** [comment]
Yes, you are absolutely right. Since I'm quite busy today I sent the fix as soon as possible :grin:

**Comment by SystemFw** [comment]
I'm thinking of a test that wouldn't involve having to create a file, since this is unit testable in principle

**Comment by aeons** [comment]
Cool. Any chance this would trigger another milestone?

**Pull request merged**
