### PR TITLE
possibly typo fixed

### PR DESCRIPTION
**Pull request by ikr0m**
I'm not sure if those are typo, but I didn't understand their meaning. At least one of them is typo

### CODE REVIEW

**Comment by ikr0m** [comment]
Initially, I also thought I might be an `enqueue` and tried to grasp the meaning of both variants:
1. `if fails will end in queue failure`
2. 'if fails will enqueue in queue failure'
First one seemed more correct. I've searched `enq` from project if there are other usages but couldn't found. I'll change it to long form as you suggested

**Comment by SystemFw** [comment]
Actually, on rereading the whole comment, I think that line (after `if fails`) is just out of date. It's not using the queue for failures anymore, but a Signal

**Comment by ikr0m** [comment]
Should it be `if fails will enqueue in signal failure`?

**Comment by SystemFw** [comment]
I think it should be something like "failures will be propagated through `done` Signal" or something like that

**Comment by SystemFw** [comment]
Thank you!

**Comment by ikr0m** [comment]
Thank you for your help!

**Pull request merged**
