### PR TITLE
Fixes the order of resource release if pure function throws.

### PR DESCRIPTION
**Pull request by AdamChlupacek**
A first PR that tackles #1128. 
This one ensures that if we encounter an error from forcing an segment we will close resources in the correct order. And puts back the new definition for `map`.

We still need to go through algebra and see if we are capturing errors from all places where they can be raised. Namely most of the `f(Right(r))` and `f(Left(err))` places. Most of them are suspended in `flatMap` of `F` but I think we should still try to capture them if we can.

### CODE REVIEW

**Comment by AdamChlupacek** [comment]
The reason why travis is not passing is since our generation of failed stream we are generating a stream which has an exception thrown from within `Segment`s transformation. I am thinking we should remove such case and have special cased test for such behaviour. As it will behave differently now.

**Comment by mpilquist** [comment]
Sounds good

**Comment by mpilquist** [comment]
@AdamChlupacek Any luck?

**Comment by AdamChlupacek** [comment]
@mpilquist sorry, I was really busy for past week :/ will try to at least get this PR into mergeable state as soon as possible.

**Comment by AdamChlupacek** [comment]
@mpilquist I really have no time for at least 2 more weeks :/ For this fix to work it is mostly only needed to change the line 200 in Algebra. That will fix the order of the resources closing. The rest of the changes was just an attempt to catch exceptions earlier. If you have time I would be glad if you could bring this through the finish line.

**Comment by mpilquist** [comment]
@AdamChlupacek Do we need this still? Since this PR, we've changed the implementation of `map` to the implementation in this PR and we did not change line 200 (now line 184) in Algebra and tests still pass.

**Comment by AdamChlupacek** [comment]
@mpilquist Interesting, I will get the latest 1.0 see if I can create a test case that would require this fix, otherwise we can close this for sure if all tests are passing.

**Comment by AdamChlupacek** [comment]
@mpilquist with getting rid of segment, this will not be required at all. I am now closing this.

**Pull request closed without merging**
