### PR TITLE
Automate publishing of microsite using Nix shell

### PR DESCRIPTION
**Pull request by gvolpe**
This is the first step in the automation of the CI build using Github actions, Nix shell & Cachix.

If this goes well, I'll try to migrate the current CI build from Travis to Github actions but at least we would have automated the publishing of the microsite every time there's a change under `site/**` or in the `README.md` file (I just made a simple update to see if it is picked up once merged).

### CODE REVIEW

**Comment by mpilquist** [comment]
Build failed b/c it's running Azul Java 1.8?

```
welcome to sbt 1.3.12 (Azul Systems, Inc. Java 1.8.0_252)
```

**Comment by kubukoz** [comment]
> Build failed b/c it's running Azul Java 1.8?
> 
> ```
> welcome to sbt 1.3.12 (Azul Systems, Inc. Java 1.8.0_252)
> ```

That's the default JRE in the sbt package. I think it can be overridden...

**Comment by gvolpe** [comment]
That's exactly what I'm doing here @kubukoz : `run: "nix-shell --run \"sbt microsite/publishMicrosite --java-home $JAVA_HOME\""`. I'll have a look...

**Comment by gvolpe** [comment]
This should fix it: https://github.com/functional-streams-for-scala/fs2/pull/1893

**Pull request merged**
