### PR TITLE
Microsite

### PR DESCRIPTION
**Pull request by keirlawson**
This PR is my first stab at setting up a FS2 microsite per #1041 

There are some limitations to this approach however after surveying various different
project's microsites I think this is probably the best possible approach.

* Links in `README.md` to other parts of the repo or site now need to be absolute,
as this file is now served as part of the site which has a different structure and
file extensions (.md converted .html).

* Having a single `tut` source directory for both site content and repo-only markdown
was not possible, as the microsite plugin insists on overriding the tut output
directory to its jekyll area in `target/`

* Currently uses the default sbt-microsite logo as there appears to be no FS2 one

* Currently not integrated into the build system, though publishing by hand is straight
forward (once the gh-pages branch is created, anyone with a private key for the
repo can simply run `sbt microsite/publishMicrosite`).  If Travis integration is
desirable it could be handled in a subsequent PR.

* I wasn't able to use the latest microsite plugin as it brings in a newer version of tut, and seemingly the fs2 docs do not compile with tut > 0.5.5

Appreciate any feedback :)

### CODE REVIEW

**Comment by keirlawson** [comment]
Its not quite the same code as in this PR, but for a rough idea of what the site will look like I published this: https://keirlawson.github.io/fs2/

To run the site locally, install Jekyll then run `sbt microsite/makeMicrositre`, then `jekyll serve` in `site/target/site`

**Comment by mpilquist** [comment]
This looks great! I upgraded to SBT 1.1 before releasing 0.10 final and that included an upgrade to the latest tut plugin. I suspect we'll be able to upgrade to latest microsites plugin now. Want to give that a shot?

**Comment by keirlawson** [comment]
Ok, updated to the latest microsites plugin.

**Comment by keirlawson** [comment]
Build failure appears unrelated to this PR?

**Comment by SystemFw** [comment]
Yeah it should be unrelated

**Pull request merged**
