### PR TITLE
Add combinator unfoldLoopEval

### PR DESCRIPTION
**Pull request by ChristopherDavenport**
Just a convenience to allow people to work with streams rather than with `Pull` when they really just want an easy stream constructor

### CODE REVIEW

**Comment by mpilquist** [comment]
Add ScalaDoc too? Should we also add `unfoldLoop` -- non-F one?

**Comment by kubukoz** [comment]
So this is like `unfold` but at least one element is produced? (since the Option is only on the "next" value we're iterating on, not on that and the produced element)

**Comment by ChristopherDavenport** [comment]
Yes. It always produces a value, but may or may not iterate. This replaces the paradigm with unfold where you unnecessarily make that initial value an option, just to iterate each layer, and pass None as the final one. This makes behavior like pagination very easy to represent.

**Comment by kubukoz** [comment]
Indeed, pagination is what I thought about. I like it :)

**Pull request merged**
