### PR TITLE
Introduced Lub1 witness and modified ++/append/evalMap/flatMap/onError/onComplete to use it in order to get better inference

### LINKED ISSUE #624: Appending pure stream to `F` stream yields in error
Seems the pure type don't fit yet correctly :
 
```scala

scala> val s1:Stream[Task,String] = Stream("A","B")
// s1: fs2.Stream[fs2.util.Task,String] = fs2.Stream$$anon$1@62cff145

scala> val s2:Stream[Pure,String] = Stream("C","D")
// s2: fs2.Stream[fs2.Pure,String] = fs2.Stream$$anon$1@2d639a64

scala> s1 ++ s2
//<console>:24: error: could not find implicit value for parameter S: fs2.util.Sub1[fs2.util.Task,fs2.Pure]

```

### PR DESCRIPTION
**Pull request by mpilquist**
Fixes #624. What do you think of this general approach? What other methods should get the `Lub1` treatment?

### CODE REVIEW

**Comment by mpilquist** [comment]
I added lubbing support for `onComplete` and `onError` as well. I think that should cover everything.

**Comment by pchlupacek** [comment]
@mpilquist to me this looks ok.  On the through side. I would like to keep separate combinators, but would like to rename throughp to perhaps throughPure to clearly mark the pure code is within. What do you think?

**Comment by mpilquist** [comment]
@pchlupacek I'm good with renaming `throughp` to `throughPure`. Use of `throughPure` would end up as a style choice in most cases, b/c our pipes are still defined for all `F[_]`. Use of `throughPure` would only be required when you have a `Stream[Nothing, A]` and you want to use a `forall F . Pipe[F, A, B]`.

**Comment by pchlupacek** [comment]
@mpilquist exactly what I meant. Thanks.

**Comment by pchiusano** [comment]
Hmm why not make the Lub a type member rather than another parameter. Then one less type parameter to specify if you ever have to annotate?

**Comment by mpilquist** [comment]
@pchiusano I tried that first, but inference doesn't work as nicely due to the lub type being invariant.

To be clear, here's what I tried:
```
sealed trait Lub1[-F[_],-G[_]] {
  type Lub[_]
  implicit def subF: Sub1[F,Lub]
  implicit def subG: Sub1[G,Lub]
}
```

**Comment by pchiusano** [comment]
Okay. Seems fine to me then.

**Pull request merged**
