### PR TITLE
Added test case showing that join/joinUnbounded release resources from outer stream too early

### PR DESCRIPTION
**Pull request by mpilquist**
See #967

### CODE REVIEW

**Comment by mpilquist** [comment]
I added a commit which fixes this test case. Since it adds 2 new primitives to the stream algebra, I'd really like to get @pchiusano to weigh in.

General idea behind the fix is the introduction of reference counting on resources along with 2 new primitives -- `ExportResources` and `ImportResources`. When a scope is closed, the reference count of each resource is decremented (via `maybeRelease`). If the count reaches 0, the finalizer is invoked. The reference count is initialized to 1.

Reference counts are incremented by using an `ExportResources` step, which returns *all* resources in the stream's scope and increments the reference count of each. We can then later use `ImportResources` on a different stream, which pulls those resources in to the scope of that stream.

**Comment by pchlupacek** [comment]
@mpilquist I like the idea of reference counting on resources, perhaps that may simplify reasoning behind Scopes too. I'll take a look on the code.

**Comment by pchlupacek** [comment]
@mpilquist obviously you were right, including the proposed fix. so unless @pchiusano has some objections to it, I suggest this will gets in as it is.

**Comment by pchlupacek** [comment]
Hm, on the other thought. Isn't the `import`/`export` thing too much low-level? Essentially we need just manually signal when acquired scope shall be released manually to outlive stream closure. However I would like still to keep it within single stream, that owning the scope, instead of having user to manage it and resources manually. 

  So I was just thinking to have something like this perhaps : 
```scala
// on Stream 

/** 
 * Allows to manually close the resource scope of the stream. 
 * Guarantees that any resources are not frees until `f` finishes its evaluation. 
 * Note however, that this applies only if the stream terminated normally. In case the stream failed or was 
 * terminated, this will not be consulted, and resources are released immediately.      
 **/
def confirmRelease(f:  F[Unit]) : Stream[F, O]  = ???   


// Then we can perhaps use it simply on any stream like 
val outerStream: Stream[F, O] = 
   source.map { inner =>
    runInner(inner)
   } 
  .confirmRelease(awaitAllInnerStreamsToTerminate)
  .onFinalize(...)
  .onError(...)

```

Then I think that the implementation perhaps may be to add to Scope's constructor this `confirm`

```final class Scope[F[_]] private (private val id: Token, private val parent: Option[Scope[F]], private val confirm: Option[F[Unit]])(implicit F: Sync[F]) ```

and then when you do `closeAndReturnFinalizers` consult whether stream was failed or interrupted, and in that case just ignore `confirm` otherwise await confirm to complete `before` running finalizers. 

This is just rough idea. What do you think ?

**Comment by mpilquist** [comment]
@pchlupacek I think that's basically what `onFinalize` does except it would register the finalizer on all scopes at or below the current scope. It's not clear to me if that will work or not though.

One thing I like about exporting resources is that we can extend it to new APIs that allow users to selectively export a resource, effectively taking over its lifecycle. No need for this now though.

**Comment by pchiusano** [comment]
Hi sorry for delayed reply, I am really swamped at the moment. My feeling is: the join/joinUnbounded functions should be fixed, and maybe for now that is done via these new stream algebra primitives, but I'm more hesitant on exposing these primitives publicly unless we are super confident they are the right approach. I haven't spent nearly as much time looking at this as y'all though, so I may just not be understanding the problem well enough. @mpilquist and @pchlupacek you should decide. :)

**Comment by mpilquist** [comment]
@pchlupacek For all `s: Stream[F,A]`, `f: A => Stream[F,B]`, finalization of resources in `s.map(f).join(n)` should be the same as `s.flatMap(f)`, regardless of failures in outer stream.

So if we went with the `confirmResources` approach, I think we'd have to invoke it no matter what (just like a finalizer) -- the difference between it and `onFinalize` is that it would register as a finalizer on the deepest right-most scope in the current scope tree whereas `onFinalize` simply registers on the current scope.

**Comment by pchlupacek** [comment]
@mpilquist I agree with what you say. Also you are right about the fact that this shall be the seam behaviour whether stream is killed failed etc... 

Lets then merge this in, as it fixes the issues and offers great flexibility.

**Pull request merged**
