### PR TITLE
Removes fs2.internal.Future and inlines the implementation in to Task

### PR DESCRIPTION
**Pull request by mpilquist**
Exploration of inlining Future in to Task. `Task#map` is optimized in this version.

Can't merge this to 0.9 because it is not a binary compatible change. If we are interested in merging this, it'll have to wait for 0.10.

### CODE REVIEW

**Comment by mpilquist** [comment]
Some benchmarks:

`jmh:run -i 10 -wi 10 -f1 -t1 --jvmArgs -Xms2g --jvmArgs -Xmx2g .*TaskBenchmark.*`

```
## Baseline

[info] Benchmark                             Mode  Cnt       Score      Error  Units
[info] TaskBenchmark.apply_12800            thrpt   10   42578.243 ± 3449.131  ops/s
[info] TaskBenchmark.current_12800          thrpt   10  226894.359 ± 9619.846  ops/s
[info] TaskBenchmark.flatMap_12800          thrpt   10    1087.893 ±  128.304  ops/s
[info] TaskBenchmark.map_12800              thrpt   10     688.280 ±  227.691  ops/s
[info] TaskBenchmark.parallelTraverse_1600  thrpt   10     172.695 ±   35.158  ops/s
[info] TaskBenchmark.race_12800             thrpt   10   19917.140 ± 1759.230  ops/s
[info] TaskBenchmark.start_12800            thrpt   10   20454.268 ± 1518.413  ops/s
[info] TaskBenchmark.traverse_1600          thrpt   10    3905.010 ±  267.189  ops/s

## Combined Task+Future

[info] Benchmark                             Mode  Cnt       Score      Error  Units
[info] TaskBenchmark.apply_12800            thrpt   10   31165.628 ± 2516.559  ops/s
[info] TaskBenchmark.current_12800          thrpt   10  210209.289 ± 7836.701  ops/s
[info] TaskBenchmark.flatMap_12800          thrpt   10    1156.195 ±   71.813  ops/s
[info] TaskBenchmark.map_12800              thrpt   10     927.821 ±   25.556  ops/s
[info] TaskBenchmark.parallelTraverse_1600  thrpt   10     178.820 ±   18.059  ops/s
[info] TaskBenchmark.race_12800             thrpt   10   20776.244 ± 2609.083  ops/s
[info] TaskBenchmark.start_12800            thrpt   10   20280.987 ± 2368.089  ops/s
[info] TaskBenchmark.traverse_1600          thrpt   10    4887.936 ±  162.897  ops/s

## Combined Task+Future + optimized map (what's in this PR)

[info] Benchmark                             Mode  Cnt       Score       Error  Units
[info] TaskBenchmark.apply_12800            thrpt   10   31328.833 ±  1805.603  ops/s
[info] TaskBenchmark.current_12800          thrpt   10  212880.162 ± 13285.017  ops/s
[info] TaskBenchmark.flatMap_12800          thrpt   10    1055.998 ±   148.690  ops/s
[info] TaskBenchmark.map_12800              thrpt   10    6105.499 ±  1453.048  ops/s
[info] TaskBenchmark.parallelTraverse_1600  thrpt   10     174.867 ±    25.236  ops/s
[info] TaskBenchmark.race_12800             thrpt   10   20517.391 ±  3043.132  ops/s
[info] TaskBenchmark.start_12800            thrpt   10   16604.427 ±  3719.253  ops/s
[info] TaskBenchmark.traverse_1600          thrpt   10    4849.137 ±   183.422  ops/s
```

**Comment by pchlupacek** [comment]
@mpilquist cool. Just some more thoughts
 - Task is trampoline + async + fail. Cannot we somehow take advantage of this and reduce boxing even further where we use Task and Trampoline together? 
-  If I read performance results correctly, apply is slower so as start. Which basically shows the only thing that really takes advantage is the optimized map. Perhaps we could get map in 0.9 and see if we cannot do better with breaking changes?

**Comment by pchiusano** [comment]
I'd be in favor of this if only because it simplifies the code.

An idea I had is that rather than `Trampoline[Unit]`, you might be able to get away with something like `List[() => Unit]` (or `Catenable[() => Unit]`). Not sure if this will be more efficient, but if you aren't using any intermediate values other than `Unit` inside the trampoline, you don't need the trampoline type's extra structure.

**Comment by mpilquist** [comment]
Running:
```
jmh:run -i 10 -wi 10 -f1 -t1 --jvmArgs -Xms2g --jvmArgs -Xmx2g .*TaskBenchmark.apply
```

Before:
```
[info] Benchmark                   Mode  Cnt      Score       Error  Units
[info] TaskBenchmark.apply_1      thrpt   10  67205.231 ±  3519.402  ops/s
[info] TaskBenchmark.apply_4      thrpt   10  70051.840 ±  4391.744  ops/s
[info] TaskBenchmark.apply_100    thrpt   10  70992.649 ±  3485.477  ops/s
[info] TaskBenchmark.apply_200    thrpt   10  70012.790 ±  6383.783  ops/s
[info] TaskBenchmark.apply_400    thrpt   10  66782.414 ±  4104.506  ops/s
[info] TaskBenchmark.apply_800    thrpt   10  67337.552 ±  2801.884  ops/s
[info] TaskBenchmark.apply_1600   thrpt   10  56217.385 ±  4751.706  ops/s
[info] TaskBenchmark.apply_3200   thrpt   10  61195.078 ±  3096.898  ops/s
[info] TaskBenchmark.apply_6400   thrpt   10  53361.838 ±  5886.136  ops/s
[info] TaskBenchmark.apply_12800  thrpt   10  42551.507 ± 10475.376  ops/s
```

After:
```
[info] Benchmark                   Mode  Cnt      Score      Error  Units
[info] TaskBenchmark.apply_1      thrpt   10  69822.907 ± 4160.554  ops/s
[info] TaskBenchmark.apply_4      thrpt   10  68595.642 ± 5185.729  ops/s
[info] TaskBenchmark.apply_100    thrpt   10  69168.573 ± 3143.320  ops/s
[info] TaskBenchmark.apply_200    thrpt   10  68160.382 ± 5151.096  ops/s
[info] TaskBenchmark.apply_400    thrpt   10  65383.883 ± 3693.868  ops/s
[info] TaskBenchmark.apply_800    thrpt   10  66677.737 ± 3053.816  ops/s
[info] TaskBenchmark.apply_1600   thrpt   10  63798.693 ± 3677.837  ops/s
[info] TaskBenchmark.apply_3200   thrpt   10  58021.485 ± 4257.027  ops/s
[info] TaskBenchmark.apply_6400   thrpt   10  54225.153 ± 3334.463  ops/s
[info] TaskBenchmark.apply_12800  thrpt   10  33395.930 ± 3661.071  ops/s
```

**Comment by mpilquist** [comment]
series/1.0

```
[info] Benchmark                   Mode  Cnt      Score      Error  Units
[info] TaskBenchmark.start_1      thrpt   10  32646.956 ± 2876.661  ops/s
[info] TaskBenchmark.start_4      thrpt   10  33973.265 ± 2864.659  ops/s
[info] TaskBenchmark.start_100    thrpt   10  37439.694 ± 4501.797  ops/s
[info] TaskBenchmark.start_200    thrpt   10  31787.168 ± 5628.920  ops/s
[info] TaskBenchmark.start_400    thrpt   10  35335.519 ± 5864.458  ops/s
[info] TaskBenchmark.start_800    thrpt   10  35978.453 ± 4012.692  ops/s
[info] TaskBenchmark.start_1600   thrpt   10  29703.707 ± 3354.544  ops/s
[info] TaskBenchmark.start_3200   thrpt   10  26195.198 ± 2073.370  ops/s
[info] TaskBenchmark.start_6400   thrpt   10  24493.295 ± 1696.017  ops/s
[info] TaskBenchmark.start_12800  thrpt   10  20293.333 ± 1249.530  ops/s
```

This branch:

```
[info] Benchmark                   Mode  Cnt      Score      Error  Units
[info] TaskBenchmark.start_1      thrpt   10  35447.752 ± 2957.790  ops/s
[info] TaskBenchmark.start_4      thrpt   10  34555.406 ±  857.775  ops/s
[info] TaskBenchmark.start_100    thrpt   10  34317.816 ±  831.255  ops/s
[info] TaskBenchmark.start_200    thrpt   10  33514.636 ± 2841.553  ops/s
[info] TaskBenchmark.start_400    thrpt   10  32577.232 ± 2882.115  ops/s
[info] TaskBenchmark.start_800    thrpt   10  37379.757 ± 1892.682  ops/s
[info] TaskBenchmark.start_1600   thrpt   10  37033.801 ± 5153.598  ops/s
[info] TaskBenchmark.start_3200   thrpt   10  26703.492 ± 3109.320  ops/s
[info] TaskBenchmark.start_6400   thrpt   10  26045.342 ± 1419.290  ops/s
[info] TaskBenchmark.start_12800  thrpt   10  20745.177 ±  506.656  ops/s
```

**Pull request merged**
