### PR TITLE
Stream.evalFilter

### PR DESCRIPTION
**Pull request by kubukoz**
Reincarnation of #1583.

### CODE REVIEW

**Comment by mpilquist** [comment]
The tests were failing on the call to `s.toList` in `asserting(_ shouldBe s.toList)`. The call to `s.toList` calls `unsafeRunSync` on an internal `IO` value that's guaranteed to be synchronous. However, the internals of IO have a bug where a separate IO compilation can confuse the check -- the workaround is here: https://github.com/typelevel/cats-effect/issues/529

**Comment by kubukoz** [comment]
That looks slightly better, thanks. Still getting some weird JS errors...

**Comment by mpilquist** [comment]
@kubukoz I got it passing. Ready to merge if you are.

**Comment by kubukoz** [comment]
Good to go!

**Pull request merged**
