### PR TITLE
Addressed additional review comments from #1240

### PR DESCRIPTION
**Pull request by mpilquist**

### CODE REVIEW

**Comment by SystemFw** [comment]
Sorry for the over-eager merge 😬

**Comment by mpilquist** [comment]
@pchlupacek With the change to `discrete`, the applicative law tests hang.

**Comment by pchlupacek** [comment]
@mpilquist not sure why is that, but the current definition of discrete is simply not correct, as the `Signal.of(1).discrete != Signal.constant(1).discrete`, and I think they shall be.

**Comment by pchlupacek** [comment]
lgtm :-)

**Pull request merged**
