### PR TITLE
Change Chunk scanLeft behaviour to match standard collections

### PR DESCRIPTION
**Pull request by culturedsys**
Fix for #1538

### CODE REVIEW

**Comment by mpilquist** [comment]
Looks like this changed the behavior of `Stream#scan`, which causes the `pause` test to fail.

**Comment by culturedsys** [comment]
The `Stream` methods `repartition`, `scan`, and `sliding` all use `Chunk#scanLeftCarry`, which depends on the same underlying implementation as `scanLeft`, so was changed by my patch. As the existing `Stream` methods depend on this behaviour, that suggests it's probably intended. I have attempted to re-implement the `Stream` methods to work with my implementation, and the existing implementations are probably more elegant (specifically, the existing behaviour of `scanLeftCarry` not including the zero element makes it easier to implement the correct behaviour for the `Stream` methods when they are called on an empty `Stream`, in which case there are no `Chunks` to operate on, and the zero element has to be manually processed).

So it may be best to leave the `Chunk` behaviour as it is. I can update my PR to include the re-implementations of the `Stream` functions if you think that's helpful; otherwise, I can submit a new PR clarifying the existing behaviour in the scaladoc.

**Comment by mpilquist** [comment]
> Another alternative would be to leave scanLeftCarry as it is, but change scanLeft to match the behaviour of List et al.

I think I like this the best -- definitely if backwards compatibility wasn't a concern. Let's see what @systemfw thinks.

**Comment by SystemFw** [comment]
> Another alternative would be to leave scanLeftCarry as it is, but change scanLeft to match the behaviour of List et al.

I like this the best as well, it's really weird to have `Chunk.scan`, which is a very well known name and concept, behave differently. Otoh `scanLeftCarry` it's our own thing and can have the most convenient semantics, which in this case would be to leave it as is since all the other methods rely on it

**Comment by culturedsys** [comment]
I've pushed a new version, which maintains the existing `scanLeftCarry` behaviour.

**Comment by mpilquist** [comment]
Looks great, thanks!

**Pull request merged**
