### PR TITLE
Fix typo & links in Guide

### PR DESCRIPTION
**Pull request by NightRa**

### CODE REVIEW

**Comment by pchiusano** [comment]
Never modify the guide directly, instead modify the source in docs/src and regenerate by switching to docs project in sbt and then doing tut or whatever the command is.

**Comment by NightRa** [comment]
@pchiusano Sure thing! Fixed.

**Comment by mpilquist** [comment]
Thanks!

**Comment by pchiusano** [comment]
Thanks @NightRa :+1:

**Pull request merged**
