### PR TITLE
Update Microsite style

### PR DESCRIPTION
**Pull request by gvolpe**
This is how it looks now:

one

two

I also had to resize the `favicon` to 32x32 otherwise it doesn't render.

### CODE REVIEW

**Comment by mpilquist** [comment]
Thanks!

**Comment by Zelenya** [comment]
@gvolpe the pngs didn't work anymore? Does it require svgs now? I've changed the icons to a cleaned up version. Now there is a mix of old and new logos. I'd like to fix it

**Comment by gvolpe** [comment]
@Zelenya right, the new microsite used Mdoc, which requires the logo to be an SVG file of 36x36 (two files, actually) and the `favicon` should be a PNG of 32x32.

It would be great if you could open a PR with better quality logos!

**Comment by Zelenya** [comment]
@gvolpe :+1:

**Pull request merged**
