### PR TITLE
Introduces Resource on PubSub#get

### PR DESCRIPTION
**Pull request by pchlupacek**
I think this shall fix the #1293, but somehow test I brought up did not pass. 

I am quite not confident if test is correct. @mpilquist can you take a very quick on QueueSpec? I just took your minimalistic example and somehow this still fails.

### CODE REVIEW

**Comment by mpilquist** [comment]
@pchlupacek Yeah, the test is correct. The dequeue is interrupted and after that completes, we enqueue 2 elements and dequeue 1 element. We must get back the first element we dequeued or otherwise, the original `dequeue` still has an outstanding effect reading from the queue.

I briefly skimmed this new implementation and I think the issue is that nothing interrupts the `Deferred#get` call upon cleanup of the resource returned from `get`. That is, the finalizer is correctly removing the token & associated state from the Queue state but not doing anything about outstanding calls to the returned `get_`.

**Comment by pchlupacek** [comment]
@mpilquist thats where I am confused. If we finalize Resource and Subscriber is cleared there shall not be a way, how that subscriber may be completed again? 

The get_ performs 
1. registration to subscribers
2. deferred.get

So if we interrupt awaiting `get`
1. cancel the `deferred.get` // note `get` is not as resource, it shall be cancellable as such 
2. unregister subscriber

that means any subsequent publishes may not see subscriber again. 

Or you saying that Resource is not cleared in this queue dequeueChunk implementation? 

```scala

      def dequeueChunk(maxSize: Int): Stream[F, A] =
          Stream.resource(pubSub.get(maxSize)).flatMap { get =>
            Stream
              .repeatEval(get)
              .unNoneTerminate
              .flatMap(Stream.chunk)
          }

```

As I read the code, when `get` is cancelled the (1) from cleanup is called and then (2) is called as a matter of finaliser on resource being invoked. 

Or am I getting this completely wrong?

**Comment by mpilquist** [comment]
See comments below:

```scala
 def dequeueChunk(maxSize: Int): Stream[F, A] =
          Stream.resource(pubSub.get(maxSize)).flatMap { get =>
            Stream.evalUnChunk(get).repeat // <-- the evaluation of `get` here isn't interrupted, it's just ignored -- the stream interpreter will evaluate `get` and when stream is interrupted, `get` will still finish in the background
          }
```

**Comment by pchlupacek** [comment]
Hm that leaves the question if we shall not have 2 implementations, really, one for F[A] where the cleanup is called on cancel, and the other with Stream[F, A] where cleanup is invoked always, when the  stream finishes. As leaving it only on resource will require the cleanup to be called always when `F` completes, which is a bit overhead for normal Get? 
What do you think ?

**Comment by mpilquist** [comment]
Yeah, I think 2 implementations could be a good solution

**Comment by pchlupacek** [comment]
Ok I'll gonna fix that. So lets close this and I open another PR

**Pull request closed without merging**
