### PR TITLE
Added unfoldSeq and unfoldSeqEval

### PR DESCRIPTION
**Pull request by almendar**
Hi,

I was asking on FS2 gitter for a way how to create a stream from a resource that has sth similar to `hasNext` like in iterator or `next` like in `ResultSet` from JDBC but I wanted to emit multiple values at once if there are ready to be published.

The solution could be to use unfold, but it can only publish a single value. 
@edmundnoble suggested I could easily write function that would publish Seq and submit a MR so here it is.

Sorry if I'm doing sth wrong but this is my first PR on github.

### CODE REVIEW

**Comment by djspiewak** [comment]
Wouldn't it be better to have an `unfoldChunk` rather than `unfoldSeq`?  That would allow full generalization to unboxed chunks, whereas the current version is either element-level or enforced `Seq` boxing.

**Comment by almendar** [comment]
Yes, that makes sense. I've added functions that accepts chunks and wrote some test that uses unboxed data.
I don't know if I should keep the `Seq` version of unfolds? It is possible to define those unfolds using the chunked version, just by transforming the state generator function result:

From `S => Option[(Seq[A],S)] ` to `S => Option[(Chunk[A],S)]` and in the same spirit in others.

**Comment by djspiewak** [comment]
I would be in favor of just removing the `Seq` versions in the interest of a smaller API.  The way I generally look at things, `Chunk` is basically just a better `Seq`.

**Comment by tscholak** [comment]
For performance reasons, would it make sense to implement the unchunked unfold and iterate in terms of these?

**Comment by tscholak** [comment]
I just realize that probably not since evaluation of `f` might be slow....

**Comment by tscholak** [comment]
In doobie, there is `processWithChunkSize`. maybe there should be `unfoldWithChunkSize` and `iterateWithChunkSize`

**Comment by mpilquist** [comment]
@almendar  :+1: from me. I agree with @djspiewak that we can do without the `Seq` variants in an effort to keep the API footprint smaller (and avoid arguments over having `Seq` variants of other APIs). Since this PR has been open a while (sorry!), I'm going to merge it as-is and then remove the `Seq` variants.

**Pull request merged**
