### PR TITLE
Added compile.lastOrError convenience function

### PR DESCRIPTION
**Pull request by mpilquist**
Per discussion in Gitter, this is a common function so we might as well provide it directly

### CODE REVIEW

**Comment by ChristopherDavenport** [comment]
My only question if this would be better by 

```scala
def lastOrError(t: Throwable)(implicit G: MonadError[G, Throwable]): G[O] = ...
```

Otherwise a lot of times this will be directly followed by `adaptError` and it confused the `NoSuchElementException` and a business logic exception as you leave streaming. Not super opinionated here, just throwing out ideas.

**Comment by SystemFw** [comment]
I'm not sure how to word it, but some comments about how this means that the stream has terminated/finished emitting would be good.

I mean things like:
```scala
Stream.hold(...).lastOrError.flatMap { .... signal never updated again...}
```

**Comment by mpilquist** [comment]
@SystemFw Note this `lastOrError` is on `CompileOps` -- I think your comment assumes it's on `Stream` instead.

@ChristopherDavenport No strong opinion here. I kind of like the current signature more as it avoids the ceremony of `new NoSuchElementException` at each call site. Also note that we'd need to take the throwable as a by-name to avoid cost of instantiating it (and filling a stack trace) in the common case.

**Comment by SystemFw** [comment]
> Note this lastOrError is on CompileOps -- I think your comment assumes it's on Stream instead.

:+1: I did assume it was on Stream, but I think the comment still holds some value, I can see people expecting that e.g. `hold` returns a `Stream[F, Signal]`, and since it's a singleton stream they can just `compile.lastOrError` and just keep working with it in `F`, which isn't the case. A similar thing would happen for finalisers. In many ways `.compile.drain` keeps you honest, but then again this helper _is_ useful, so not quite sure how to word a possible cautionary comment. Don't let this hold merging though

**Comment by ChristopherDavenport** [comment]
Good call. I like this solution. I'm doing the whole ceremony now, so it's a reduction in boilerplate regardless.

**Comment by mpilquist** [comment]
@SystemFw Yeah I see what you mean. If you come up with wording that works, let's update it in a new PR.

**Pull request merged**
